### PR TITLE
fix: resolve problem in match component

### PR DESCRIPTION
**Pull request by viniarruda**
If have much people, the match component crash and does not occupy full screen.

### CODE REVIEW

**Comment by emmanuelkant** [comment]
@viniarruda The problem of does not occupate all screen was resolved with position fixed instead absolute. Good call. But you change the color string too. The color continues white but the string have change. I think this is a piece of code unnecessary in commit.

**Comment by viniarruda** [comment]
I will adjust. Probably it’s because my prettier config

**Review by emmanuelkant — APPROVED** [review]
It's good for me.

**Review by diego3g — APPROVED** [review]

**Comment by viniarruda** [comment]
Hey guys, make the merge please

**Pull request merged**
