### PR TITLE
dracula theme option

### PR DESCRIPTION
**Pull request by tclemos**
Hey @diego3g, I'm sure you are very busy with the Bootcamp arrangement, but since you love the **Dracula** theme, I thought you would like this.

I just implemented as fast as possible and in the simplest way. I didn't like to change the app file to add the **switch**, but this was the fastest way I've found to share the theme selector between both screens.

Feel free to merge or decline the PR 😄 

Screen Shot 2019-08-13 at 11 01 03

Screen Shot 2019-08-13 at 11 02 43

### CODE REVIEW

**Comment by emmanuelkant** [comment]
To have a Dracula theme it is sounds good for me. It will be nice.

**Comment by viniarruda** [comment]
Good job!

**Comment by tclemos** [comment]
Hey @diego3g, I'm sure you are very busy with the Bootcamp arrangement, but since you love the **Dracula** theme, I thought you would like this.

I just implemented as fast as possible and in the simplest way. I didn't like to change the app file to add the **switch**, but this was the fastest way I've found to share the theme selector between both screens.

Feel free to merge or decline the PR 😄

**Comment by tclemos** [comment]
Screen Shot 2019-08-13 at 11 01 03

Screen Shot 2019-08-13 at 11 02 43

**Comment by emmanuelkant** [comment]
@tclemos, the images have helped a lot for we can see the final product. To help @diego3g you would add a label of enhancement. So that, is easier for him understand all context. Furthermore, it will be more professional hahaha : )

**Comment by tclemos** [comment]
> @tclemos, the images have helped a lot for we can see the final product. To help @diego3g you would add a label of enhancement. So that, is easier for him understand all context. Furthermore, it will be more professional hahaha : )

The options to add Reviewers, Labels and etc are disabled for me 😢

**Comment by diego3g** [comment]
Wooooow, that's much more beautiful then the light theme. Thanks!

**Pull request merged**
